--- #YAML:1.0
name:                Validator
version:             0.01
abstract:            Input params validator
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    AGAVA::AGE::Framework::Library::XML::XPath::Cached: 0
    Cache::FileCache:              0
    Class::Accessor::Fast:         0
    JSON::XS:                      0
    Mail::RFC822::Address:         0
    XML::SAX::ParserFactory:       0
    XML::Simple:                   0
    XML::Validator::Schema:        0
    XML::XPath:                    0
    XML::XPath::XMLParser:         0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Alex Nosoff <plcgi1@gmail.com>
